version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=sql
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  permissionsapi:
    build: .
    ports:
      - "5005:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=n5now;User Id=sa;Password=sql;
    depends_on:
      - sqlserver
